name: CI Secret Test

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print secret length
        run: |
          echo "Secret length:"
          echo ${#MY_SECRET}
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}

